### PR TITLE
gcli: fix paged cmd iteration

### LINKED ISSUE #126: gencli: paged RPC commands only return 1 item regardless of page_size
The command generated for paged RPCs makes a duplicate call that doesn't make sense. The duplicate call needs to be removed.

### PR DESCRIPTION
**Pull request by noahdietz**
Fixes #126 

* fix paged cmd iteration
* remove broken integration test from gcli testing make target

### CODE REVIEW

File: internal/gencli/cmd_file.go [hunk 1]
```diff
@@ -277,24 +277,21 @@ var {{$methodCmdVar}} = &cobra.Command{
 		{{ end }}
 		{{ else if and .Paged (not .IsLRO ) }}
 		// get requested page
-		page, err := iter.Next()
-		if err != nil {
+		data := make(map[string]interface{})
+		items := []interface{}{}
```
Comment (pongad) [inline internal/gencli/cmd_file.go]: var items []interface{}

File: internal/gencli/cmd_file.go [hunk 2]
```diff
@@ -277,24 +277,21 @@ var {{$methodCmdVar}} = &cobra.Command{
...
+		for i := {{ $inputVar }}.PageSize; i > 0; i-- {
```
Comment (pongad) [inline internal/gencli/cmd_file.go]: Do we want this to just print an item from one page? I think `i := 0; i < input.PageSize; i++` is better. Note that we have no hard guarantee that we only make one RPC here, since a server might return fewer than PageSize elements. Is that OK for our use case?

Comment (noahdietz) [reply internal/gencli/cmd_file.go]: I agree its better, but some `PageSize` field definitions are `int32` (i.e. all of them gapic-showcase). Initializing a new variable `i := 0` creates an `int`, resulting in a type mismatch between the `int32` `PageSize` and `i`. Flipping the iteration logic like so means the `0` in `i > 0` is created as an `int32`.

Comment (pongad) [reply internal/gencli/cmd_file.go]: Yeah you're right. Let's put that in a comment then.

Comment (noahdietz) [reply internal/gencli/cmd_file.go]: > Note that we have no hard guarantee that we only make one RPC here, since a server might return fewer than PageSize elements. Is that OK for our use case?

I am OK with this. There is no way for the consumer to know if the server returned the `PageSize` number of elements in 1 RPC anyways, so we can't do anything about it.

File: internal/gencli/cmd_file.go (hunk 1 above)
Comment (noahdietz) [reply internal/gencli/cmd_file.go]: Done!

File: internal/gencli/cmd_file.go (hunk 2 above)
Comment (noahdietz) [reply internal/gencli/cmd_file.go]: Comment added regarding PageSize decrement semantics.

**Comment by noahdietz** [comment]
Updated, PTAL!
